# Generated by Django 5.2.6 on 2025-09-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Rcuisine',
            field=models.TextField(max_length=200),
        ),
    ]
