# Generated by Django 5.2.6 on 2025-09-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_restaurant_rating_alter_restaurant_rcuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Restroname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='Rcuisine',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='Rurl',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(default='Add type of cuisine here', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(default='https://static.vecteezy.com/system/resources/previews/052/792/818/non_2x/restaurant-logo-design-vector.jpg', max_length=500),
        ),
    ]
