# Generated by Django 5.2.6 on 2025-09-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/1147/1147856.png', max_length=300),
        ),
    ]
