# Generated by Django 5.2.6 on 2025-09-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/1147/1147856.png'),
        ),
    ]
